spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root    # TODO: ユーザー名を入力
    password: pass  # TODO: パスワードを入力
    # MySQL ドライバを明示的に使用
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 明示的に hikaricp を利用することを宣言
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: world-schema
      connection-timeout: 20000
      # minimum-idle: 10
      # maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
# serverのIPを指定
server:
  port: 8081
